language: php

branches:
  only:
    - master
    - stable

matrix:
  include:
  - os: linux
    dist: "trusty"
    php: "5.6"
  - os: linux
    dist: "trusty"
    php: "nightly"
  - os: linux
    dist: "xenial"
    php: "7.1"
  - os: linux
    dist: "xenial"
    php: "nightly"
  - os: linux
    dist: "bionic"
    php: "7.4"
  - os: linux
    dist: "bionic"
    php: "nightly"
  - os: osx
    osx_image: xcode11
    language: shell
  - os: osx
    osx_image: xcode11.1
    language: shell
  - os: osx
    osx_image: xcode11.2
    language: shell
  - os: osx
    osx_image: xcode11.3
    language: shell
  allow_failures:
  - os: linux
    dist: "trusty"
    php: "5.6"
  - os: linux
    dist: "trusty"
    php: "7.1"
  - os: linux
    dist: "trusty"
    php: "nightly"
  - os: linux
    dist: "xenial"
    php: "5.6"
  - os: linux
    dist: "xenial"
    php: "7.1"
  - os: linux
    dist: "xenial"
    php: "nightly"
  - os: linux
    dist: "bionic"
    php: "nightly"
  - os: osx
    osx_image: xcode6.4
    language: shell
  - os: osx
    osx_image: xcode7.3
    language: shell
  - os: osx
    osx_image: xcode7.3
    language: shell
  - os: osx
    osx_image: xcode8
    language: shell
  - os: osx
    osx_image: xcode8.3
    language: shell
  - os: osx
    osx_image: xcode9
    language: shell
  - os: osx
    osx_image: xcode9
    language: shell
  - os: osx
    osx_image: xcode9.2
    language: shell
  - os: osx
    osx_image: xcode9.3
    language: shell
  - os: osx
    osx_image: xcode9.4
    language: shell
  - os: osx
    osx_image: xcode10
    language: shell
  - os: osx
    osx_image: xcode10.1
    language: shell
  - os: osx
    osx_image: xcode11
    language: shell
  - os: osx
    osx_image: xcode11.1
    language: shell

before_install:
      - if [ $TRAVIS_OS_NAME == osx ] ; then brew upgrade || true ; fi
      - if [ $TRAVIS_OS_NAME == osx ] ; then brew install php7 $INSTALL || true ; fi

before_script:
      - make clean

script:
      - make test

after_script:
      - make clean
