language: php
sudo: false

branches:
  only:
    - master
    - stable

matrix:
  include:
  - os: linux
    dist: "Trusty"
    php: "5.6"
  - os: linux
    dist: "Trusty"
    php: "7.1"
  - os: linux
    dist: "Trusty"
    php: "nightly"
  - os: linux
    dist: "Xenial"
    php: "5.6"
  - os: linux
    dist: "Xenial"
    php: "7.1"
  - os: linux
    dist: "Xenial"
    php: "nightly"
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic
  - os: osx
    osx_image: xcode9
    language: generic
  - os: osx
    osx_image: xcode9.4
    language: generic
  - os: osx
    osx_image: xcode10
    language: generic
  - os: osx
    osx_image: xcode10.1
    language: generic
  allow_failures:
  - os: linux
    dist: "Xenial"
    php: "5.6"
  - os: linux
    dist: "Xenial"
    php: "7.1"
  - os: linux
    dist: "Xenial"
    php: "nightly"
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic
  - os: osx
    osx_image: xcode9
    language: generic
  - os: osx
    osx_image: xcode9.2
    language: generic
  - os: osx
    osx_image: xcode9.3
    language: generic


before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew upgrade || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install php7 $INSTALL || true ; fi

install: "true"

after_script:
  - make clean

before_script:
  - make clean

script:
  - make test
