language: php
sudo: false

branches:
  only:
    - master

matrix:
  include:
  - os: linux
    php: "5.6"
  - os: linux
    php: "7.1"
  - os: linux
    php: "nightly"
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew upgrade || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install php7 $INSTALL || true ; fi

install: "true"
# command to run tests
script:
  - php -l webroot/PiAP/pages/*.php
